version: "3"
networks:
  dbwebb:

services:
  db:
    build:
      context: ./Spark-mysql
      dockerfile: Dockerfile
    container_name: mysql-db
    image: spark-backend-db:v1.0
    restart: always
    ports:
      - 3308:3306
    networks:
      dbwebb:

  cache:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      dbwebb:

  server:
    build:
      context: ./Spark-API-v1
      target: builder
      dockerfile: Dockerfile
    container_name: api-server
    image: spark-backend-server:v1.0
    env_file:
      - "./Spark-API-v1/.env"
    volumes:
      - "./Spark-API-v1:/app"
    restart: always
    depends_on:
      - db
      - cache
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      dbwebb:
    links:
      - db:mysql-db
      - cache:cache

volumes:
  cache:
    driver: local
