version: "3"
networks:
  dbwebb:

services:
  db:
    build:
      context: ./Spark-mysql
      dockerfile: Dockerfile
    container_name: mysql-db
    image: spark-backend-db:v1.0
    restart: always
    ports:
      - 3308:3306
    networks:
      dbwebb:

  server:
    build:
      context: ./Spark-API-v1
      target: builder
      dockerfile: Dockerfile
    container_name: api-server
    image: spark-backend-server:v1.0
    env_file:
      - "./.env"
    volumes:
      - "./Spark-API-v1:/app"
    restart: always
    depends_on:
      - db
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"
    networks:
      dbwebb:
    links:
      - db:mysql-db
      - bike-server:bike-server

  bike-server:
    build:
      context: ./Spark-bike-server
      dockerfile: Dockerfile
    container_name: bike-server
    # command: python3 ./main.py
    command: sh -c "sleep 10 ; python3 ./main.py"
    restart: always
    ports:
      - 9898:9898/udp
    depends_on:
      - db
    networks:
      dbwebb:
    links:
      - db:mysql-db
